#!/bin/bash
set -e
cd /home/bcloud/torch2aie/examples/gemm_asymmetric_tile_buffering/config1
export PATH="/home/bcloud/mlir-aie/npu2_40_toolchain/bin:/home/bcloud/torch2aie/toolchain/bin:$PATH"
export PYTHONPATH="/home/bcloud/torch2aie/toolchain/mlir_aie/python"
export LD_LIBRARY_PATH="/home/bcloud/mlir-aie/npu2_40_toolchain/lib:$LD_LIBRARY_PATH"
export TORCH2AIE_PYTHON="/home/bcloud/torch2aie/.venv/bin/python"
export AIETOOLS_DIR="/home/bcloud/torch2aie/toolchain/aietools"

# Force rebuild of multi-token QKV with 40-col aiecc
echo "=== Remove old xclbin ==="
rm -f build/final_256x1024x4096_128x64x128.xclbin build/insts_256x1024x4096_128x64x128.txt

echo "=== Generate MLIR ==="
# MLIR is generated by Python, not aiecc — use standard venv
/home/bcloud/torch2aie/.venv/bin/python n2_core_placed.py -M 256 -K 1024 -N 4096 -m 128 -k 64 -n 128 > build/aie_256x1024x4096_128x64x128.mlir 2>&1
echo "MLIR lines: $(wc -l < build/aie_256x1024x4096_128x64x128.mlir)"

echo "=== Compile with 40-col aiecc ==="
/home/bcloud/mlir-aie/npu2_40_toolchain/bin/aiecc \
  --aietools="${AIETOOLS_DIR}" \
  --alloc-scheme=basic-sequential \
  --aie-generate-xclbin --no-compile-host \
  --xclbin-name=final_256x1024x4096_128x64x128.xclbin \
  --unified --dynamic-objFifos \
  --aie-generate-npu-insts \
  --npu-insts-name=insts_256x1024x4096_128x64x128.txt \
  build/aie_256x1024x4096_128x64x128.mlir 2>&1 | tail -10

echo "=== New instruction count ==="
wc -c build/insts_256x1024x4096_128x64x128.txt

# Test
/home/bcloud/npu-sandbox/npu-infer/build/test_mt_gemm3 2>&1
